In [3]:
#standartization
import numpy as np
import pandas as pd
from scipy import stats
iris = pd.read_csv(r"C:\Users\Fuat\Learning Machine Learning\Iris.csv")

In [4]:
iris.head(3)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa

In [11]:

LengthCm = iris['SepalLengthCm']
meanSepalLength = np.mean(LengthCm)
stdSepalLength = np.std(LengthCm)
X= (np.arange(150, dtype=float))
print(X)

for i in range(150):
    X[i] = ((LengthCm[i]-meanSepalLength)/stdSepalLength)

[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.
  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.
  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.
  42.  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.
  56.  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.
  70.  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.
  84.  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.
  98.  99. 100. 101. 102. 103. 104. 105. 106. 107. 108. 109. 110. 111.
 112. 113. 114. 115. 116. 117. 118. 119. 120. 121. 122. 123. 124. 125.
 126. 127. 128. 129. 130. 131. 132. 133. 134. 135. 136. 137. 138. 139.
 140. 141. 142. 143. 144. 145. 146. 147. 148. 149.]

In [9]:
X

array([-0.90068117, -1.14301691, -1.38535265, -1.50652052, -1.02184904,
       -0.53717756, -1.50652052, -1.02184904, -1.74885626, -1.14301691,
       -0.53717756, -1.26418478, -1.26418478, -1.87002413, -0.05250608,
       -0.17367395, -0.53717756, -0.90068117, -0.17367395, -0.90068117,
       -0.53717756, -0.90068117, -1.50652052, -0.90068117, -1.26418478,
       -1.02184904, -1.02184904, -0.7795133 , -0.7795133 , -1.38535265,
       -1.26418478, -0.53717756, -0.7795133 , -0.41600969, -1.14301691,
       -1.02184904, -0.41600969, -1.14301691, -1.74885626, -0.90068117,
       -1.02184904, -1.62768839, -1.74885626, -1.02184904, -0.90068117,
       -1.26418478, -0.90068117, -1.50652052, -0.65834543, -1.02184904,
        1.40150837,  0.67450115,  1.2803405 , -0.41600969,  0.79566902,
       -0.17367395,  0.55333328, -1.14301691,  0.91683689, -0.7795133 ,
       -1.02184904,  0.06866179,  0.18982966,  0.31099753, -0.29484182,
        1.03800476, -0.29484182, -0.05250608,  0.4321654 , -0.29484182,
        0.06866179,  0.31099753,  0.55333328,  0.31099753,  0.67450115,
        0.91683689,  1.15917263,  1.03800476,  0.18982966, -0.17367395,
       -0.41600969, -0.41600969, -0.05250608,  0.18982966, -0.53717756,
        0.18982966,  1.03800476,  0.55333328, -0.29484182, -0.41600969,
       -0.41600969,  0.31099753, -0.05250608, -1.02184904, -0.29484182,
       -0.17367395, -0.17367395,  0.4321654 , -0.90068117, -0.17367395,
        0.55333328, -0.05250608,  1.52267624,  0.55333328,  0.79566902,
        2.12851559, -1.14301691,  1.76501198,  1.03800476,  1.64384411,
        0.79566902,  0.67450115,  1.15917263, -0.17367395, -0.05250608,
        0.67450115,  0.79566902,  2.24968346,  2.24968346,  0.18982966,
        1.2803405 , -0.29484182,  2.24968346,  0.55333328,  1.03800476,
        1.64384411,  0.4321654 ,  0.31099753,  0.67450115,  1.64384411,
        1.88617985,  2.4920192 ,  0.67450115,  0.55333328,  0.31099753,
        2.24968346,  0.55333328,  0.67450115,  0.18982966,  1.2803405 ,
        1.03800476,  1.2803405 , -0.05250608,  1.15917263,  1.03800476,
        1.03800476,  0.55333328,  0.79566902,  0.4321654 ,  0.06866179])

In [14]:
# normalization
maxLength = np.max(LengthCm)
minLength = np.min(LengthCm)
Y= (np.arange(150, dtype=float))
print(Y)
for i in range(150):
    Y[i] = ((Y[i]- minLength)/(maxLength - minLength))

[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.
  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.
  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.
  42.  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.
  56.  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.
  70.  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.
  84.  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.
  98.  99. 100. 101. 102. 103. 104. 105. 106. 107. 108. 109. 110. 111.
 112. 113. 114. 115. 116. 117. 118. 119. 120. 121. 122. 123. 124. 125.
 126. 127. 128. 129. 130. 131. 132. 133. 134. 135. 136. 137. 138. 139.
 140. 141. 142. 143. 144. 145. 146. 147. 148. 149.]

In [15]:
Y

array([-1.19444444, -0.91666667, -0.63888889, -0.36111111, -0.08333333,
        0.19444444,  0.47222222,  0.75      ,  1.02777778,  1.30555556,
        1.58333333,  1.86111111,  2.13888889,  2.41666667,  2.69444444,
        2.97222222,  3.25      ,  3.52777778,  3.80555556,  4.08333333,
        4.36111111,  4.63888889,  4.91666667,  5.19444444,  5.47222222,
        5.75      ,  6.02777778,  6.30555556,  6.58333333,  6.86111111,
        7.13888889,  7.41666667,  7.69444444,  7.97222222,  8.25      ,
        8.52777778,  8.80555556,  9.08333333,  9.36111111,  9.63888889,
        9.91666667, 10.19444444, 10.47222222, 10.75      , 11.02777778,
       11.30555556, 11.58333333, 11.86111111, 12.13888889, 12.41666667,
       12.69444444, 12.97222222, 13.25      , 13.52777778, 13.80555556,
       14.08333333, 14.36111111, 14.63888889, 14.91666667, 15.19444444,
       15.47222222, 15.75      , 16.02777778, 16.30555556, 16.58333333,
       16.86111111, 17.13888889, 17.41666667, 17.69444444, 17.97222222,
       18.25      , 18.52777778, 18.80555556, 19.08333333, 19.36111111,
       19.63888889, 19.91666667, 20.19444444, 20.47222222, 20.75      ,
       21.02777778, 21.30555556, 21.58333333, 21.86111111, 22.13888889,
       22.41666667, 22.69444444, 22.97222222, 23.25      , 23.52777778,
       23.80555556, 24.08333333, 24.36111111, 24.63888889, 24.91666667,
       25.19444444, 25.47222222, 25.75      , 26.02777778, 26.30555556,
       26.58333333, 26.86111111, 27.13888889, 27.41666667, 27.69444444,
       27.97222222, 28.25      , 28.52777778, 28.80555556, 29.08333333,
       29.36111111, 29.63888889, 29.91666667, 30.19444444, 30.47222222,
       30.75      , 31.02777778, 31.30555556, 31.58333333, 31.86111111,
       32.13888889, 32.41666667, 32.69444444, 32.97222222, 33.25      ,
       33.52777778, 33.80555556, 34.08333333, 34.36111111, 34.63888889,
       34.91666667, 35.19444444, 35.47222222, 35.75      , 36.02777778,
       36.30555556, 36.58333333, 36.86111111, 37.13888889, 37.41666667,
       37.69444444, 37.97222222, 38.25      , 38.52777778, 38.80555556,
       39.08333333, 39.36111111, 39.63888889, 39.91666667, 40.19444444])